services:
  local-fileserver:
    image: nginx:alpine
    container_name: local-fileserver
    volumes:
      - /data/mediverse/scripts:/usr/share/nginx/html/data/mediverse/scripts:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9033/data/mediverse/scripts/test.txt || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
